project:
  type: website

website:
  title: "Mark Barrett"
  site-url: https://mokeeire.github.io/QuartoWebsite
  repo-url: https://github.com/MokeEire/QuartoWebsite
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.md
        text: Blog
    right:
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/Mmm_JuicyFruit
      - icon: github
        aria-label: github
        href: https://github.com/MokeEire
  page-footer: 
    left: "Copyright 2022, Mark Barrett" 
    right:
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/Mmm_JuicyFruit
      - icon: github
        aria-label: github
        href: https://github.com/MokeEire

format:
  html:
    theme: flatly
    css: styles.css

filters:
  - fold_results.lua

execute:
  freeze: auto