project:
  type: website

website:
  title: "Mark Barrett"
  site-url: https://deft-florentine-57fcaf.netlify.app/
  repo-url: https://github.com/MokeEire/QuartoWebsite
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - blog.md
      - data-visualization.md
    right:
      - icon: github
        aria-label: github
        href: https://github.com/MokeEire
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/markkbarrett/
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/Mmm_JuicyFruit
      - icon: bar-chart-steps
        aria-label: data-viz
        menu: 
          - text: "Tableau Public"
            href: https://public.tableau.com/app/profile/mokeeire
  page-footer: 
    left: "Copyright 2022, Mark Barrett" 
    right:
      - icon: github
        aria-label: github
        href: https://github.com/MokeEire
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/markkbarrett/
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/Mmm_JuicyFruit

format:
  html:
    theme: flatly
    css: styles.css

filters:
  - fold_results.lua
  - lightbox

execute:
  freeze: auto